const keywordColors = [
    `alicealue`,
    `antiquewhite`,
    `aqua`,
    `aquamarine`,
    `azure`,
    `beige`,
    `bisque`,
    `black`,
    `blanchedalmond`,
    `blue`,
    `blueviolet`,
    `brown`,
    `burlywood`,
    `cadetblue`,
    `chartreuse`,
    `chocolate`,
    `coral`,
    `cornflowerblue`,
    `cornsilk`,
    `crimson`,
    `cyan`,
    `darkblue`,
    `darkcyan`,
    `darkgoldenrod`,
    `darkgray`,
    `darkgrey`,
    `darkgreen`,
    `darkkhaki`,
    `darkmagenta`,
    `darkolivegreen`,
    `darkorange`,
    `darkorchid`,
    `darkred`,
    `darksalmon`,
    `darkseagreen`,
    `darkslateblue`,
    `darkslategray`,
    `darkslategrey`,
    `darkturquoise`,
    `darkviolet`,
    `deeppink`,
    `deepskyblue`,
    `dimgray`,
    `dimgrey`,
    `dodgerblue`,
    `firebrick`,
    `floralwhite`,
    `forestgreen`,
    `fuchsia`,
    `gainsboro`,
    `ghostwhite`,
    `gold`,
    `goldenrod`,
    `gray`,
    `grey`,
    `green`,
    `greenyellow`,
    `honeydew`,
    `hotpink`,
    `indianred`,
    `indigo`,
    `ivory`,
    `khaki`,
    `lavender`,
    `lavenderblush`,
    `lawngreen`,
    `lemonchiffon`,
    `lightblue`,
    `lightcoral`,
    `lightcyan`,
    `lightgoldenrodyellow`,
    `lightgray`,
    `lightgrey`,
    `lightgreen`,
    `lightpink`,
    `lightsalmon`,
    `lightseagreen`,
    `lightskyblue`,
    `lightslategray`,
    `lightslategrey`,
    `lightsteelblue`,
    `lightyellow`,
    `lime`,
    `limegreen`,
    `linen`,
    `magenta`,
    `maroon`,
    `mediumaquamarine`,
    `mediumblue`,
    `mediumorchid`,
    `mediumpurple`,
    `mediumseagreen`,
    `mediumslateblue`,
    `mediumspringgreen`,
    `mediumturquoise`,
    `mediumvioletred`,
    `midnightblue`,
    `mintcream`,
    `mistyrose`,
    `moccasin`,
    `navajowhite`,
    `navy`,
    `oldlace`,
    `olive`,
    `olivedrab`,
    `orange`,
    `orangered`,
    `orchid`,
    `palegoldenrod`,
    `palegreen`,
    `paleturquoise`,
    `palevioletred`,
    `papayawhip`,
    `peachpuff`,
    `peru`,
    `pink`,
    `plum`,
    `powderblue`,
    `purple`,
    `red`,
    `rosybrown`,
    `royalblue`,
    `saddlebrown`,
    `salmon`,
    `sandybrown`,
    `seagreen`,
    `seashell`,
    `sienna`,
    `silver`,
    `skyblue`,
    `slateblue`,
    `slategray`,
    `slategrey`,
    `snow`,
    `springgreen`,
    `steelblue`,
    `tan`,
    `teal`,
    `thistle`,
    `tomato`,
    `turquoise`,
    `violet`,
    `wheat`,
    `white`,
    `whitesmoke`,
    `yellow`,
    `yellowgreen`,
  ];
  const hexRegex = /^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$/;
  
  // Checks user input to see if it is either a color keyword or a hexadecimal value.
  function validateColor(input) {
    // Catches if user input is somehow null before checking further.
    if (input === null) {
      console.log("Please enter a valid color keyword or hexadecimal value.");
      return false;
    }
    if (keywordColors.includes(input.toLowerCase()) || hexRegex.test(input)) {
      return true;
    } else {
      console.log("Please enter a valid color keyword or hexadecimal value.");
      return false;
    }
  }
  
  module.exports = validateColor;